sudo: required
script:
- make all sign
after_failure:
- cat $HOME/*_result/last_operation.log
before_install:
- 'openssl aes-256-cbc -K $encrypted_07480c1749ca_key -iv $encrypted_07480c1749ca_iv
  -in sec.enc -out sec -d'
env:
  global:
    secure: jEQ5qNl2R27mM5i215NveQYk8zotIriZP06ttbV0qWwzAR86/yamVVp7YIcY60eZRNlJpDs2aWhZzv9RxUfNzL2A360qPyQt9NR8OaYLGBexo9zSvWBXd7yIuS+C2+FiWiUvJO130FWqE6yPsnbCA20QtJVHNtMtZ1k5KzoyT5wjk5GYHuxtQzaNc/6lP0XTApMhh78qP/plYmK2+92RCpgKo8o10/Ox3mw+reT09P1wi8l8G8ZMyU1erTWbnk5v44Y5EMo7IcC1foXNtzkTr5b/IuD7WnpClALGWZhmqOQdFySFD4t1F8qhWDpS/Kt5bARU68iLOa3SowZ/kUBPWmwgw++1oGni1l8G6ybpaHzUEQ+aytOO9b4fu5xpCWXe4fLasCzrFL6jtfkaWKpY/co0/bjDiXkCA2lUZWQaaWIFbQAIxfrrlsH+nnAmMuUNYdgr1Y7hfdBRBhcDQlALMBc/vj0uSPwsR9F70VnCL6OaCLpd0tAhzgo8kUoD9YzP6OYUN/xnZWqdbl4eTEIaSH/y1HbWZ3FQHkBohwj9AnSNmazTSRVomE8dMjwynB6ow6I/Yq866wO6ZX9RP10funVOtBWCpwMNAJ8RPjgO9KqIQLHX500foAeIabtcx0n+YYaKGKn8aTB22gsg9LNaM5ioxbhf3LlxhxXXbgiyTAs=
